# Generated by Django 3.1 on 2020-08-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of a category.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the service the link points to.', max_length=50)),
                ('link', models.CharField(help_text='Enter the link.', max_length=100)),
                ('description', models.TextField(help_text='Enter a description for the link.', max_length=300)),
            ],
        ),
    ]
